stages:
  - test

image: archlinux:base-devel

before_script:
  - pacman -Syu --noconfirm base-devel git cmake unzip ninja tree-sitter curl lua51-lpeg lua51-mpack unibilium libluv libtermkey libuv libvterm luajit msgpack-c

run_test_filetype_comprehensive:
  stage: test
  artifacts:
    expire_in: 1 week
    untracked: true
  allow_failure: true
  script:
    - .ci/build_neovim.sh
    - .ci/run_test_filetype.sh
